### ISSUE TITLE
AppVeyor build ê būn-tê

### ISSUE THREAD

**Issue by ngoohebi** [i3thuan5/weasel#3]
Chit-má ē hián-sī siōng sin ê build sī chhò-gō͘, in-ūi Github Release token ê būn-tê.

In-ūi chit-má góa ê kháu-chō kap @sih4sing5hong5  ê kháu-chō lóng ē cháu.
Góa ê sī sêng-kong--ê.
https://ci.appveyor.com/project/shiami/weasel/builds/31063848

@sih4sing5hong5 --ê in-ūi m̄-sī góa ê kháu-chō sán-seng ê token só͘-pái ē sit-pāi.
https://ci.appveyor.com/project/sih4sing5hong5/weasel/builds/31063847

M̄-koh góa m̄-chai i sī án-ne kéng beh hián-sī tó 1-ê.

Kiàn-gī @sih4sing5hong5  iōng lí ê kháu-chō khì sin-chhéng:
https://www.appveyor.com/docs/deployment/github/

Chiah koh khì thè-ōaⁿ script lāi-té ê token.

**Comment by sih4sing5hong5** [comment]
好，我才閣揣時間看
